sudo: false
language: python
python:
- '3.4'
install:
- pip install .
- pip install -r requirements/test.txt
- pip install python-coveralls
script:
- make all
after_success:
- coveralls --ignore-errors
